# Generated by Django 3.1.6 on 2021-03-04 18:17

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210228_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer_profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=users.models.employer_profile.nameFile),
        ),
    ]
