# Generated by Django 3.1.6 on 2021-03-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20210227_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('On Hold', 'On Hold'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='On Hold', max_length=20),
        ),
    ]
