# Generated by Django 3.1.6 on 2021-03-09 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210304_2347'),
        ('management', '0004_auto_20210304_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='PA_Phases',
            fields=[
                ('phase_id', models.AutoField(primary_key=True, serialize=False)),
                ('phase_name', models.CharField(max_length=300)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companies')),
            ],
        ),
        migrations.CreateModel(
            name='phases_question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=600)),
                ('phase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.pa_phases')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('weeks', models.DateField()),
                ('review', models.CharField(choices=[('Exceptional', 'Exceptional'), ('Meet Requirements', 'Meet requirements'), ('Gets By', 'Gets By'), ('Needs Improvement', 'Needs Improvement')], max_length=25)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companies')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employers')),
                ('phase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.pa_phases')),
                ('questions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.phases_question')),
            ],
        ),
    ]
