# Generated by Django 3.1.6 on 2021-03-15 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210304_2347'),
        ('management', '0006_auto_20210313_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='choices',
            fields=[
                ('choice_id', models.AutoField(primary_key=True, serialize=False)),
                ('choice_name', models.CharField(max_length=200)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companies')),
            ],
        ),
    ]
