# Generated by Django 3.1.6 on 2021-03-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='marks',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
