# Generated by Django 3.1.6 on 2021-03-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_choices_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='marks',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choices',
            name='choice_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(default='No comment', max_length=300),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=200),
        ),
    ]
